language: php

php:
  - 5.6
  - 7.0

services:
  - mysql

env:
  global:
    - DB_DATABASE=myapp_test
    - DB_USERNAME=travis
    - DB_PASSWORD=

before_install:
  - mysql -e 'create database myapp_test;'
  - echo 'APP_KEY=xxx' > .env

install:
  - composer install --no-interaction --prefer-dist
  - php artisan key:generate
  - php artisan jwt:secret
  - php artisan migrate --force

script: vendor/bin/phpunit
